/*
  Warnings:

  - The values [CREATE_COMPANY,READ_COMPANY,UPDATE_COMPANY,DELETE_COMPANY,CREATE_STORE,READ_STORE,UPDATE_STORE,DELETE_STORE,CREATE_USER,READ_USER,UPDATE_USER,DELETE_USER,CREATE_PRODUCT,READ_PRODUCT,UPDATE_PRODUCT,DELETE_PRODUCT,READ_STOCK,READ_ORDER,UPDATE_ORDER,DELETE_ORDER,READ_PAYMENT,REFUND_PAYMENT] on the enum `Permission` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Permission_new" AS ENUM ('VIEW_DASHBOARD', 'VIEW_REPORTS', 'MANAGE_COMPANY', 'MANAGE_SUBSCRIPTION', 'MANAGE_STORES', 'MANAGE_USERS', 'MANAGE_PRODUCTS', 'MANAGE_STOCK', 'CREATE_ORDER', 'PROCESS_PAYMENT', 'PRINT_RECEIPT');
ALTER TABLE "UserPermission" ALTER COLUMN "permission" TYPE "Permission_new" USING ("permission"::text::"Permission_new");
ALTER TYPE "Permission" RENAME TO "Permission_old";
ALTER TYPE "Permission_new" RENAME TO "Permission";
DROP TYPE "Permission_old";
COMMIT;
